// src/app/components/input/input.component.ts
import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnInit,
  Output,
  ViewChild,
  AfterViewInit,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';

@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
})
export class InputComponent implements OnInit, AfterViewInit, OnChanges {
  @ViewChild('inputElem', { read: ElementRef })
  inputElem: ElementRef<HTMLInputElement>;

  @Input() disabled = false;
  @Input() label;

  @Input() value = '';
  @Input() isNumber = false;
  @Output() valueChange = new EventEmitter();

  constructor(private cdr: ChangeDetectorRef) {}

  ngAfterViewInit(): void {
    this.cdr.detectChanges();
  }

  ngOnInit(): void {
    this.cdr.detectChanges();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['value']) {
      this.value = changes['value'].currentValue
    }
    this.cdr.detectChanges();
  }

  onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    this.value = target.value
  }

  blur(event: FocusEvent) {
    if (this.isNumber) {
      const nVal = Number(this.value)
      this.valueChange.emit(nVal)
    } else {
      this.valueChange.emit(this.value)
    }
  }
}

<div class="flex flex-col items-start justify-start flex-shrink">
    <x-label *ngIf="label" class="text-white text-sm">{{ label }}</x-label>
    <x-input #inputElem class="w-full max-w-none" [value]="value" (input)="onChange($event)" (blur)="blur($event)" [disabled]="disabled"></x-input>
</div>

// src/ui/components/Input/index.tsx
import React from 'react';

type Props = React.HTMLProps<HTMLInputElement> & {
  onChange?: (value: string) => void;
  onBlur?: (value: string) => void;
};

export function Input(props: Props) {
  function onChange(event: React.FormEvent<HTMLInputElement>) {
    const target = event.target as HTMLInputElement;
    if (props.onChange) {
      props.onChange(target.value);
    }
  }

  function onBlur(event: React.FocusEvent<HTMLInputElement>) {
    const target = event.target as HTMLInputElement;
    if (props.onBlur) {
      props.onBlur(target.value);
    }
  }

  return (
    <div className='flex flex-col items-start w-full flex-grow'>
      <label className='text-white text-xs mb-1'>{props.label}</label>
      <input
        className='w-full bg-neutral-600 p-1 text-white text-xs focus:outline-none focus:outline-blue-400 disabled:text-neutral-400'
        {...props}
        onChange={onChange}
        onBlur={onBlur}
      />
    </div>
  );
}
